from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    
    question: str = Field(...,min_length=1, description="the user question")
    model_config = {
        "json_schema_extra": {
            "example": {
                "tenant_id": "company_acme_prod",
                "question": "What is our company policy regarding remote hybrid work allowances?"
            }
        }
    }
    
    
    
    
    
class SourceChunk(BaseModel):
    chunk_index: int = Field(..., description="The sequential index of the text chunk.")
    chunk_content: str = Field(..., description="The actual text string extracted from the document.")
    distance: float = Field(..., description="The calculated cosine distance score (lower means closer match).")
    
    
        
class ChatResponse(BaseModel):
    answer: str = Field(..., description="The context-verified semantic answer generated by the core model.")
    source: list[SourceChunk] = Field(..., description="the actual context from teh document with index and distance ")
        