from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    
    question: str = Field(...,min_length=1, description="the user question")
    model_config = {
        "json_schema_extra": {
            "example": {
                "tenant_id": "company_acme_prod",
                "question": "What is our company policy regarding remote hybrid work allowances?"
            }
        }
    }
    
    
    
    
    
    
class ChatResponse(BaseModel):
    answer: str = Field(..., description="The context-verified semantic answer generated by the core model.")
    
        